import AppKit
import SwiftUI
import Combine

@MainActor
final class NotchViewModel: ObservableObject {
    @Published var nudge: Nudge?
    @Published var expanded = false
    @Published var hovering = false
    @Published var hasNotch = true
    @Published var notchWidth: CGFloat = 200
    @Published var notchHeight: CGFloat = 32
    @Published var avatar = AvatarConfig()
    @Published var image: NSImage?
    @Published var moodImage: NSImage?
    @Published var moodRevealed = false
    /// Maa & Papa mode: her picture, shown beside his in a wider block.
    @Published var maaImage: NSImage?
    @Published var duo = false
    @Published var doneLabel = "OK"
    @Published var snoozeLabel = "10 min"
    /// Bumped once per throw; the view runs its flight keyframes off it.
    @Published var chappalThrows = 0

    /// Frames (SwiftUI global coordinates) of the two solid parts, for hit testing.
    var blockRect: CGRect = .zero
    var bubbleRect: CGRect = .zero

    var onDone: (() -> Void)?
    var onSnooze: (() -> Void)?
    var onOpenSettings: (() -> Void)?
}

/// Only the block and the bubble take clicks; everything else falls through to
/// whatever is behind the transparent panel.
final class NotchHostingView<Content: View>: NSHostingView<Content> {
    var hitRegions: () -> [CGRect] = { [] }

    override func hitTest(_ point: NSPoint) -> NSView? {
        let local = convert(point, from: superview)
        let flippedY = isFlipped ? local.y : bounds.height - local.y
        let p = CGPoint(x: local.x, y: flippedY)
        guard hitRegions().contains(where: { $0.insetBy(dx: -4, dy: -4).contains(p) }) else { return nil }
        return super.hitTest(point)
    }
}

@MainActor
final class NotchController {
    /// Layout constants shared with NotchView.
    static let blockMinWidth: CGFloat = 210
    static let blockBodyHeight: CGFloat = 118
    static let bubbleWidth: CGFloat = 320
    /// Distance from the black body of the block to the tip of the bubble's tail.
    static let bubbleGap: CGFloat = 6
    static let flare: CGFloat = 14
    static let shadowPad: CGFloat = 30
    static let panelBodyHeight: CGFloat = 230

    /// Extra block width when Maa peeks out beside him.
    static let duoExtraWidth: CGFloat = 120

    static func blockWidth(forNotch notchWidth: CGFloat, duo: Bool = false) -> CGFloat {
        max(blockMinWidth, notchWidth + 36) + (duo ? duoExtraWidth : 0)
    }

    let model = NotchViewModel()

    var onSnooze: ((Nudge) -> Void)?
    var onDone: ((Nudge) -> Void)?
    /// The nudge timed out with no tap at all.
    var onIgnored: ((Nudge) -> Void)?
    var onOpenSettings: (() -> Void)?

    private let store: SettingsStore
    private var panel: NotchPanel?
    private var hideTimer: Timer?
    private var moodWork: DispatchWorkItem?
    private var throwWork: [DispatchWorkItem] = []
    /// Whoosh and slap, generated by Scripts/chappal_sound.py. Copied per play so two
    /// throws close together both sound.
    private static let slap: NSSound? = Bundle.main.url(forResource: "chappal", withExtension: "wav")
        .flatMap { NSSound(contentsOf: $0, byReference: true) }
    private var cancellables = Set<AnyCancellable>()

    private(set) var isVisible = false

    init(store: SettingsStore) {
        self.store = store
        model.onDone = { [weak self] in self?.tapDone() }
        model.onSnooze = { [weak self] in self?.tapSnooze() }
        model.onOpenSettings = { [weak self] in
            self?.hide()
            self?.onOpenSettings?()
        }
        model.$hovering
            .removeDuplicates()
            .sink { [weak self] hovering in
                guard let self, self.isVisible else { return }
                if hovering {
                    self.hideTimer?.invalidate()
                } else {
                    self.scheduleHide(after: 1.8)
                }
            }
            .store(in: &cancellables)
    }

    // MARK: - Show / hide

    func show(_ nudge: Nudge) {
        let settings = store.settings
        let geo = NotchGeometry.current(placement: settings.placement)

        model.avatar = settings.avatar
        // He pops out with his usual face, then reacts a beat later.
        let store = AvatarImageStore.shared
        let pro = LicenseManager.shared.isPro
        model.image = store.effectiveImage(for: .neutral, allowCustom: pro)
        model.moodImage = store.effectiveImage(for: nudge.expression, allowCustom: pro)
        model.moodRevealed = false
        let maa = nudge.coSpeaker == nil ? nil : AvatarImageStore.bundledMaa()
        model.maaImage = maa
        model.duo = maa != nil
        moodWork?.cancel()
        let reveal = DispatchWorkItem { [weak self] in
            withAnimation(.easeInOut(duration: 0.45)) { self?.model.moodRevealed = true }
        }
        moodWork = reveal
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.75, execute: reveal)
        model.hasNotch = geo.hasNotch
        model.notchWidth = geo.notchWidth
        model.notchHeight = geo.notchHeight
        let pack = MessageLibrary.pack(settings.language)
        model.doneLabel = nudge.coSpeaker == nil ? pack.done : pack.doneTogether
        model.snoozeLabel = pack.snooze
        model.nudge = nudge
        cancelChappal()
        if nudge.chappal { scheduleChappal(sound: settings.soundEnabled) }

        let panel = ensurePanel()
        panel.setFrame(frame(for: geo, tall: nudge.chappal, duo: model.duo), display: false)

        hideTimer?.invalidate()
        isVisible = true

        if panel.isVisible {
            withAnimation(.spring(response: 0.35, dampingFraction: 0.75)) {
                model.expanded = true
            }
        } else {
            model.expanded = false
            panel.alphaValue = 1
            panel.orderFrontRegardless()
            DispatchQueue.main.async { [weak self] in
                withAnimation(.spring(response: 0.45, dampingFraction: 0.78)) {
                    self?.model.expanded = true
                }
            }
        }

        if settings.soundEnabled {
            NSSound(named: "Pop")?.play()
        }
        // The Chappal Treatment runs about three and a half seconds; he stays for all of it.
        scheduleHide(after: max(nudge.chappal ? 7 : 4, settings.displaySeconds))
    }

    // MARK: - Chappal Treatment

    /// Timeline after he pops out: face turns angry (0.75s), then two throws, at
    /// 1.4s and 2.5s. Each chappal leaves the notch 0.18s in and reaches you at 0.55s;
    /// those offsets match the keyframes in NotchView.
    private func scheduleChappal(sound: Bool) {
        func at(_ t: TimeInterval, _ block: @escaping () -> Void) {
            let w = DispatchWorkItem(block: block)
            throwWork.append(w)
            DispatchQueue.main.asyncAfter(deadline: .now() + t, execute: w)
        }
        for start in [1.4, 2.5] {
            at(start) { [weak self] in self?.model.chappalThrows += 1 }
            at(start + 0.18) {
                guard sound else { return }
                if let slap = Self.slap?.copy() as? NSSound { slap.play() } else { NSSound(named: "Blow")?.play() }
            }
            at(start + 0.55) {
                NSHapticFeedbackManager.defaultPerformer.perform(.levelChange, performanceTime: .now)
            }
        }
    }

    private func cancelChappal() {
        throwWork.forEach { $0.cancel() }
        throwWork.removeAll()
    }

    func hide() {
        hideTimer?.invalidate()
        moodWork?.cancel()
        guard isVisible else { return }
        isVisible = false
        // Quick, clean retract straight back into the notch.
        cancelChappal()
        withAnimation(.easeInOut(duration: 0.26)) {
            model.expanded = false
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.3) { [weak self] in
            guard let self, !self.isVisible else { return }
            self.panel?.orderOut(nil)
            self.model.nudge = nil
            self.model.hovering = false
            self.model.moodRevealed = false
        }
    }

    /// Flash a reaction face, then retract.
    private func react(with expression: Expression, then completion: @escaping () -> Void) {
        hideTimer?.invalidate()
        moodWork?.cancel()
        let store = AvatarImageStore.shared
        guard model.avatar.useImage,
              let face = store.effectiveImage(for: expression, allowCustom: LicenseManager.shared.isPro),
              face !== model.moodImage else {
            completion()
            return
        }
        model.moodImage = face
        withAnimation(.easeInOut(duration: 0.25)) { model.moodRevealed = true }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.65, execute: completion)
    }

    private func scheduleHide(after seconds: TimeInterval) {
        hideTimer?.invalidate()
        let t = Timer(timeInterval: seconds, repeats: false) { [weak self] _ in
            Task { @MainActor in
                guard let self else { return }
                if self.model.hovering { return }
                if let n = self.model.nudge { self.onIgnored?(n) }
                self.hide()
            }
        }
        RunLoop.main.add(t, forMode: .common)
        hideTimer = t
    }

    private func tapDone() {
        if let n = model.nudge { onDone?(n) }
        react(with: .happy) { [weak self] in self?.hide() }
    }

    private func tapSnooze() {
        if let n = model.nudge { onSnooze?(n) }
        react(with: .stern) { [weak self] in self?.hide() }
    }

    // MARK: - Panel plumbing

    private func ensurePanel() -> NotchPanel {
        if let panel { return panel }
        let p = NotchPanel()
        let host = NotchHostingView(rootView: NotchView(model: model))
        host.hitRegions = { [weak model] in
            guard let model else { return [] }
            return [model.blockRect, model.bubbleRect]
        }
        host.wantsLayer = true
        host.layer?.backgroundColor = .clear
        p.contentView = host
        panel = p
        return p
    }

    /// `tall` gives the chappal room to fly down the screen and out to the sides; the
    /// extra area is transparent and click-through like the rest of the panel.
    private func frame(for geo: NotchGeometry, tall: Bool = false, duo: Bool = false) -> CGRect {
        let blockWidth = Self.blockWidth(forNotch: geo.notchWidth, duo: duo)
        let pad = tall ? NotchView.throwSidePad : 0
        let width = pad * 2 + Self.flare * 2 + blockWidth + Self.bubbleGap + Self.bubbleWidth + Self.shadowPad
        let x = geo.notchRect.midX - Self.flare - blockWidth / 2 - pad
        let body = tall ? Self.blockBodyHeight + NotchView.throwTravel + 120 : Self.panelBodyHeight
        if geo.hasNotch {
            let height = geo.notchHeight + body
            return CGRect(x: x, y: geo.screen.frame.maxY - height, width: width, height: height)
        } else {
            let height = body
            let top = geo.notchRect.minY - 6
            return CGRect(x: x, y: top - height, width: width, height: height)
        }
    }
}
